# Edit Distance

## Recursive Brute Force Solution

In [2]:
def edit_distance(s: str, t: str) -> int:
    
    def distance(i: int, j: int) -> int:
        if i == 0: return j   # s is empty, j insertions
        if j == 0: return i   # t is empty, i deletions
        
        # case 1 - change
        if s[i-1] == t[j-1]:
            changes = distance(i-1, j-1)
        else:
            changes = 1 + distance(i-1, j-1)
            
        # case 2 - deletions
        deletions = 1 + distance(i-1, j) 
        
        # case 3 - insertions
        insertions = 1 + distance(i, j-1)
        
        return min(changes, insertions, deletions)
    
    return distance(len(s), len(t))
        

In [3]:
s = "snowy"
t = "sunny"
print(edit_distance(s,t))

3


In [4]:
s = 'polynomial'
t = 'exponential'
print(edit_distance(s,t))

6


## Edit Distance - Dynamic Programming

In [5]:
import numpy as np
def edit_distance(s: str, t: str) -> int:
    dist = np.zeros((len(s) + 1, len(t) + 1))
    
    # initialize the first row
    for j in range(len(t) + 1): dist[0][j] = j
        
    # initialize the first column
    for i in range(len(s) + 1): dist[i][0] = i
        
    print(dist)
        
    

In [6]:
edit_distance("horse", "ror")

[[0. 1. 2. 3.]
 [1. 0. 0. 0.]
 [2. 0. 0. 0.]
 [3. 0. 0. 0.]
 [4. 0. 0. 0.]
 [5. 0. 0. 0.]]
